routes/web.php
<?php

use App\Http\Controllers\ActivityController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware(['auth', 'admin'])->group(function(){
    Route::get('/', function(){
        return view('dashboard');
    })->name('dashboard');
    Route::resource('activities', ActivityController::class)->except('show');
    Route::get('/users', [UserController::class, 'index'])->name('users');
});


Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'role',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function activities()
    {
        return $this->belongsToMany(Activity::class, 'user_activities');
    }

    public function isAdmin():bool
    {
        return (bool) $this->role == config('user.roles.admin');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\Auth\LoginRequest;
use App\Jobs\AttachUserToAllActivities;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('users.index', ['users' => User::where('role', config('user.roles.user'))->withCount('activities')->paginate(10)]);
    }

    public function login(LoginRequest $request){
        if(!Auth::attempt($request->validated())) return response()->json(['status' => false, 'message' => 'Invalid credentials'], 401);

        $user = User::where('email', $request->email)->first();

        return response()->json([
            'status' => true,
            'message' => 'User Logged In Successfully',
            'token' => $user->createToken("API TOKEN")->plainTextToken
        ], 200);
    }

    public function registerUser(Request $request){
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => 'required'
        ]);

        if ($validator->fails()) {
            return response()->json([
                'status' => false,
                'message' => 'Validation Error',
                'errors' => $validator->errors()
            ], 422);
        }

        $data = $validator->validated();
        $data['password'] = bcrypt($data['password']);
        $user = User::create($data);

        $this->dispatch(new AttachUserToAllActivities($user));

        return response()->json([
            'status' => true,
            'message' => 'User Created Successfully',
            'token' => $user->createToken("API TOKEN")->plainTextToken
        ], 200);
    }

    public function getUserActivities(Request $request)
    {
        $activities = $request->user()->activities();
        try{
            $rangeArray = explode('-', $request->range);
            $from_date = null;
            $to_date = null;
            if(count($rangeArray) > 0){
                $from_date = Carbon::createFromFormat('d/n/y', trim($rangeArray[0]))->format('Y-m-d');
                if(isset($rangeArray[1])) $to_date = Carbon::createFromFormat('d/n/y', trim($rangeArray[1]))->format('Y-m-d');
            }
            if($from_date){
                $activities = $activities->where('activity_date', '>=', $from_date);
            }

            if ($to_date) {
                $activities = $activities->where('activity_date', '<=', $to_date);
            }

            return response()->json([
                'status' => true,
                'message' => 'Activities retrieved successfully!',
                'data' => $activities->get()
            ]);
        }catch(\Exception $e){
            return response()->json([
                'status' => false,
                'message' => 'Error retrieving activities!',
                'error' => $e->getMessage()
            ], 400);
        }

    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/users/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="px-8 pt-8 pb-4">
            <div class="lg:flex lg:items-center lg:justify-between">
                <div class="flex-1 min-w-0">
                    <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">
                        All Users
                    </h2>
                </div>
            </div>
        </div>
    </x-slot>

    <div class="py-2">
        <div class="py-4">
            <div class="py-2">
                <div class="flex flex-col overflow-hidden">
                    @if($users->count() < 1) <div class="flex flex-col items-center justify-center">
                        <img src="{{ asset('images/empty.svg') }}" alt="empty state image"
                            class="object-cover object-center w-1/3 mb-3">
                        <h4 class="mb-1 text-lg font-medium text-blue-900">No users have registered yet!</h4>
                </div>
                @else
                <div class="px-2 -my-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
                    <div class="inline-block min-w-full overflow-hidden align-middle">
                        <table class="min-w-full">
                            <thead>
                                <tr>
                                    <th class="px-4 py-4 text-sm font-medium text-center text-gray-600">
                                        S/N
                                    </th>
                                    <th class="px-4 py-4 text-sm font-medium text-center text-gray-600">
                                        Name
                                    </th>
                                    <th class="px-4 py-4 text-sm font-medium text-center text-gray-600">
                                        No. of Activities
                                    </th>
                                    <th class="px-4 py-4 text-sm font-medium text-center text-gray-600">
                                        Registered On
                                    </th>
                                    <th class="px-4 py-4 text-sm font-medium text-center text-gray-600">
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @php($sn = 0)
                                @foreach($users as $user)
                                @php($sn++)
                                <tr
                                    class="bg-white border-b border-gray-100 shadow last:border-b-0 sm:rounded-lg hover:bg-gray-100">
                                    <td
                                        class="px-4 py-4 text-sm font-medium text-center text-gray-600 whitespace-no-wrap">
                                        {{ $sn + ((request()->get('page', 1) - 1) * 10) }}
                                    </td>
                                    <td
                                        class="px-4 py-4 text-sm font-medium text-left text-gray-600 whitespace-no-wrap">
                                            <h4 class="text-base font-bold text-gray-800">{{ $user->name }}</h4>
                                            <p>{{ $user->email }}</p>
                                    </td>
                                    <td
                                        class="px-4 py-4 text-sm font-medium text-center text-gray-600 whitespace-no-wrap">
                                        {{ $user->activities_count }}
                                    </td>
                                    <td
                                        class="px-4 py-4 text-sm font-medium text-center text-gray-600 whitespace-no-wrap">
                                        {{ $user->created_at->diffForHumans() }}
                                    </td>
                                    <td>
                                        <a href="{{ route('activities.index') }}?user_id={{ $user->id }}"
                                            class="text-blue-500 hover:text-blue-600 hover:underline">View Activities</a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="mt-6">
                    {{ $users->links() }}
                </div>
                @endif
            </div>
        </div>

    </div>
</x-app-layout>