routes/web.php
<?php

use App\Http\Controllers\ActivityController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware(['auth', 'admin'])->group(function(){
    Route::get('/', function(){
        return view('dashboard');
    })->name('dashboard');
    Route::resource('activities', ActivityController::class)->except('show');
    Route::get('/users', [UserController::class, 'index'])->name('users');
});


Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Models/Activity.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Activity extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'description', 'image', 'activity_date', 'global_activity_id'];

    protected $casts = ['activity_date' => 'date'];

    public function users()
    {
        return $this->belongsToMany(User::class, 'user_activities');
    }
}

app/Http/Controllers/ActivityController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Activity;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Http\Requests\ActivityRequest;
use App\Jobs\AttachActivityToAllUsers;
use App\Http\Resources\ActivityCalendarResource;

class ActivityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $query = Activity::query();
        if($request->month){
            $year = $request->year ?? date('Y');
            $activities = $query->whereMonth('activity_date', $request->month)->whereYear('activity_date', $year)->get();
            return response()->json(ActivityCalendarResource::collection($activities));
        }

        $user = $request->user_id ? User::where('id', $request->user_id)->first() : null;
        if($user){
            $activities = $user->activities()->paginate(10)->appends($request->all());
        }else{
            $activities = $query->paginate(10)->appends($request->all());
        }
        return view('activities.index', compact('activities', 'user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('activities.create', [
            'users' => User::where('role', config('user.roles.user'))->get(),
            'user' => request()->get('user_id') ? User::where('id', request()->get('user_id'))->first() : null,
            'date' => request()->get('date') ? date('Y-m-d', strtotime(request()->get('date'))) : '',
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  ActivityRequest  $request
     *
     */
    public function store(ActivityRequest $request)
    {
        $data = $request->validated();
        if($this->checkDateActivities($data['activity_date'])) {
            return back()->with('error', 'You cannot add more than 4 activities for each day!');
        }

        if ($request->has('activity_image')) {
            $file = $request->file('activity_image');
            $name = Str::slug($data['title']) . time() . '.' . $file->getClientOriginalExtension();
            $data['image'] = $file->storePubliclyAs("images", $name, 'public');
        }
        $activity = Activity::create($data);
        if(isset($data['user_id']) && !is_null($data['user_id'])){
            $user = User::where('id', $data['user_id'])->first();
            if(!$user) return back()->with('error', 'User not found!');
            $user->activities()->attach($activity);
        }else{
            $this->dispatch(new AttachActivityToAllUsers($activity));
        }

        return back()->with('success', 'Activity created successfully!');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Activity  $activity
     * @return \Illuminate\Http\Response
     */
    public function edit(Activity $activity)
    {
        $user = request()->get('user_id') ? User::where('id', request()->get('user_id'))->first() : null;
        if (is_null($user) && !is_null($activity->global_activity_id)) {
            $user = $activity->users()->first();
        }
        return view('activities.edit', [
            'users' => User::where('role', config('user.roles.user'))->get(),
            'activity' => $activity,
            'user' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  ActivityRequest  $request
     * @param  \App\Models\Activity  $activity
     * @return \Illuminate\Http\Response
     */
    public function update(ActivityRequest $request, Activity $activity)
    {
        $data = $request->validated();
        if ($this->checkDateActivities($data['activity_date'], $activity)) {
            return back()->with('error', 'You cannot add more than 4 activities for each day!');
        }

        if ($request->has('activity_image')) {
            $file = $request->file('activity_image');
            $name = Str::slug($data['title']) . time() . '.'. $file->getClientOriginalExtension();
            $data['image'] = $file->storePubliclyAs("images", $name, 'public');
        }
        if (isset($data['user_id']) && !is_null($data['user_id'])) {
            $user = User::where('id', $data['user_id'])->first();
            if (!$user) return back()->with('error', 'User not found!');
            if((!$activity->global_activity_id && $user->activities()->where('activities.id', $activity->id)->doesntExist()) || ($activity->global_activity_id && $user->activities()->where('activities.id', $activity->id)->doesntExist()) || (!$activity->global_activity_id && $user->activities()->where('activities.id', $activity->id)->exists())){
                if($user->activities()->where('activities.id', $activity->id)->exists()) $user->activities()->detach($activity);
                $this->createNewActivityForUser($user, $activity, $data);
                return back()->with('success', 'Activity updated for user successfully!');
            }
        }
        if(isset($data['image']) && $activity->image && file_exists(public_path("storage/$activity->image"))){
            unlink(public_path("storage/$activity->image"));
        }
        $activity->update($data);
        return back()->with('success', 'Activity updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Activity  $activity
     * @return \Illuminate\Http\Response
     */
    public function destroy(Activity $activity)
    {
        if($activity->delete()){
            return back()->with('success', 'Activity deleted successfully!');
        }
    }

    private function createNewActivityForUser(User $user, Activity $activity, $data){
        $newActivity = $activity->replicate();
        $newActivity->global_activity_id = $activity->id;
        $newActivity->title = $data['title'];
        $newActivity->description = $data['description'];
        $newActivity->activity_date = $data['activity_date'];
        $newActivity->save();
        $user->activities()->attach($newActivity);
    }

    private function checkDateActivities($date, $except = null)
    {
        $query = Activity::whereDate('activity_date', $date);
        if($except) $query->where('id', '!=', $except->id);
        if($query->count() >= 4) return true;
        return false;
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/activities/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="px-8 pt-8 pb-4">
            <div class="lg:flex lg:items-center lg:justify-between">
                <div class="flex-1 min-w-0">
                    <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">
                        Create New Activity {{ $user ? " for {$user->name}" : "" }}
                    </h2>
                </div>
            </div>
        </div>
    </x-slot>

    <div class="py-12">
        <div class="mx-auto space-y-6 max-w-7xl sm:px-6 lg:px-8">
            <div class="p-4 bg-white shadow sm:p-8 sm:rounded-lg">
                <div class="max-w-xl">
                    <form method="post" action="{{ route('activities.store') }}" enctype="multipart/form-data" class="mt-6 space-y-6">
                        @csrf
                        <div>
                            <x-input-label for="title" value="Title" />
                            <x-text-input id="title" name="title" type="text" class="block w-full mt-1" :value="old('title')" required autofocus autocomplete="title" />
                            <x-input-error class="mt-2" :messages="$errors->get('title')" />
                        </div>

                        <div>
                            <x-input-label for="desc" value="Description" />
                            <x-text-input id="desc" name="description" type="text" class="block w-full mt-1" :value="old('description')" required autocomplete="description" />
                            <x-input-error class="mt-2" :messages="$errors->get('description')" />
                        </div>

                        <div>
                            <x-input-label for="date" value="Activity Date" />
                            <x-text-input id="date" name="activity_date" type="date" class="block w-full mt-1" :value="old('activity_date') ?: $date" required autocomplete="activity_date" />
                            <x-input-error class="mt-2" :messages="$errors->get('activity_date')" />
                        </div>

                        <div>
                            <x-input-label for="img" value="Activity Image" />
                            <x-text-input id="img" name="activity_image" type="file" accept="image/*" class="block w-full mt-1" />
                            <x-input-error class="mt-2" :messages="$errors->get('activity_image')" />
                        </div>

                        @if($user)
                            <x-text-input type="hidden" name="user_id" :value="$user->id" />
                        @else
                            <x-input-label for="user" value="Create Activity For User" />
                            <select name="user_id" id="user" class="inline-flex justify-center w-full px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-100">
                                <option @selected(old('user_id') == '') value="">All Users</option>
                                @foreach($users as $usr)
                                <option @selected(old('user_id') == $usr->id || $user ? $user->id == $usr->id : false) value="{{ $usr->id }}">{{ $usr->name }}</option>
                                @endforeach
                            </select>
                            <x-input-error class="mt-2" :messages="$errors->get('user_id')" />
                        @endif

                        <div class="flex items-center gap-4">
                            <x-primary-button>Create</x-primary-button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/activities/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="px-8 pt-8 pb-4">
            <div class="lg:flex lg:items-center lg:justify-between">
                <div class="flex-1 min-w-0">
                    <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">
                        Edit {{ $activity->title }} {{ $user ? " for {$user->name}" : "" }}
                    </h2>
                </div>
            </div>
        </div>
    </x-slot>

    <div class="py-12">
        <div class="mx-auto space-y-6 max-w-7xl sm:px-6 lg:px-8">
            <div class="p-4 bg-white shadow sm:p-8 sm:rounded-lg">
                <div class="max-w-xl">
                    <form method="post" action="{{ route('activities.update', $activity) }}" enctype="multipart/form-data" class="mt-6 space-y-6">
                        @csrf
                        @method('PUT')
                        <div>
                            <x-input-label for="title" value="Title" />
                            <x-text-input id="title" name="title" type="text" class="block w-full mt-1" :value="old('title', $activity->title)" required autofocus autocomplete="title" />
                            <x-input-error class="mt-2" :messages="$errors->get('title')" />
                        </div>

                        <div>
                            <x-input-label for="desc" value="Description" />
                            <x-text-input id="desc" name="description" type="text" class="block w-full mt-1" :value="old('description', $activity->description)" required autocomplete="description" />
                            <x-input-error class="mt-2" :messages="$errors->get('description')" />
                        </div>

                        <div>
                            <x-input-label for="date" value="Activity Date" />
                            <x-text-input id="date" name="activity_date" type="date" class="block w-full mt-1" :value="old('activity_date', $activity->activity_date->format('Y-m-d'))" required autocomplete="activity_date" />
                            <x-input-error class="mt-2" :messages="$errors->get('activity_date')" />
                        </div>

                        <div>
                            <x-input-label for="img" value="Activity Image" />
                            <x-text-input id="img" name="activity_image" type="file" accept="image/*" class="block w-full mt-1" />
                            <x-input-error class="mt-2" :messages="$errors->get('activity_image')" />
                        </div>

                        @if($user)
                            <x-text-input type="hidden" name="user_id" :value="$user->id" />
                        @else
                            <x-input-label for="user" value="Create Activity For User" />
                            <select name="user_id" id="user" class="inline-flex justify-center w-full px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-100">
                                <option @selected(old('user_id') == '') value="">All Users</option>
                                @foreach($users as $usr)
                                <option @selected(old('user_id') == $usr->id || $user ? $user->id == $usr->id : false) value="{{ $usr->id }}">{{ $usr->name }}</option>
                                @endforeach
                            </select>
                            <x-input-error class="mt-2" :messages="$errors->get('user_id')" />
                        @endif

                        <div class="flex items-center gap-4">
                            <x-primary-button>Update</x-primary-button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/activities/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="px-8 pt-8 pb-4">
            <div class="lg:flex lg:items-center lg:justify-between">
                <div class="flex-1 min-w-0">
                    <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">
                        {{ $user ? "{$user->name}'s " : '' }} Activities
                    </h2>
                </div>
                <div class="flex mt-5 lg:mt-0 lg:ml-4">
                    <span class="block">
                        <a href="{{ $user ? route('activities.create')."?user_id={$user->id}" : route('activities.create') }}"
                            class="inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-2 -ml-1 text-gray-500" fill="none"
                                viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M12 4v16m8-8H4" />
                            </svg>
                            Add New
                        </a>
                    </span>
                </div>
            </div>
        </div>
    </x-slot>

    <div class="py-2">
        <div class="py-4">
            <div class="py-2">
                <div class="flex flex-col overflow-hidden">
                    @if($activities->count() < 1) <div class="flex flex-col items-center justify-center">
                        <img src="{{ asset('images/empty.svg') }}" alt="empty state image"
                            class="object-cover object-center w-1/3 mb-3">
                        <h4 class="mb-1 text-lg font-medium text-blue-900">No activities have been added yet!</h4>
                </div>
                @else
                <div class="px-2 -my-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
                    <div class="inline-block min-w-full overflow-hidden align-middle">
                        <table class="min-w-full">
                            <thead>
                                <tr>
                                    <th class="px-4 py-4 text-sm font-medium text-center text-gray-600">
                                        S/N
                                    </th>
                                    <th class="px-4 py-4 text-sm font-medium text-center text-gray-600">
                                        Title
                                    </th>
                                    <th class="px-4 py-4 text-sm font-medium text-center text-gray-600">
                                        Activity Date
                                    </th>
                                    <th class="px-4 py-4 text-sm font-medium text-center text-gray-600">
                                        Added On
                                    </th>
                                    <th class="px-4 py-4 text-sm font-medium text-center text-gray-600">
                                    </th>
                                    <th class="px-4 py-4 text-sm font-medium text-center text-gray-600">
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @php($sn = 0)
                                @foreach($activities as $activity)
                                @php($sn++)
                                <tr
                                    class="bg-white border-b border-gray-100 shadow last:border-b-0 sm:rounded-lg hover:bg-gray-100">
                                    <td
                                        class="px-4 py-4 text-sm font-medium text-center text-gray-600 whitespace-no-wrap">
                                        {{ $sn + ((request()->get('page', 1) - 1) * 10) }}
                                    </td>
                                    <td
                                        class="flex items-center px-4 py-4 text-sm font-medium text-left text-gray-600 whitespace-no-wrap">
                                        <div class="mr-2">
                                            @if($activity->image)
                                            <img src="{{ $activity->image }}" alt="{{ $activity->title }}" class="object-cover object-center w-10 h-10 rounded-full">
                                            @else
                                            @php
                                            preg_match_all('/(?<=\b)\w/iu',$activity->title,$matches);
                                            $acronym = mb_strtoupper(implode('',$matches[0]))
                                            @endphp
                                            <img src="https://via.placeholder.com/200x200.png?text={{ $acronym }}" alt="{{ $activity->title }}" class="object-cover object-center w-10 h-10 rounded-full">
                                            @endif
                                        </div>
                                        <div>
                                            <h4 class="text-base font-bold text-gray-800">{{ $activity->title }}</h4>
                                            <p>{{ $activity->description }}</p>
                                        </div>
                                    </td>
                                    <td
                                        class="px-4 py-4 text-sm font-medium text-center text-gray-600 whitespace-no-wrap">
                                        {{ $activity->activity_date->format('d M Y') }}
                                    </td>
                                    <td
                                        class="px-4 py-4 text-sm font-medium text-center text-gray-600 whitespace-no-wrap">
                                        {{ $activity->created_at->diffForHumans() }}
                                    </td>
                                    <td>
                                        <a href="{{ $user ? route('activities.edit', $activity)."?user_id={$user->id}" : route('activities.edit', $activity) }}"
                                            class="text-blue-500 hover:text-blue-600 hover:underline">Edit</a>
                                    </td>
                                    <td>
                                        <form action="{{ route('activities.destroy', $activity) }}" method="post"
                                            ref="deleteForm">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                        <a href="#" v-on:click="submitDelete()"
                                            class="text-red-500 hover:text-red-600 hover:underline">Delete</a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="mt-6">
                    {{ $activities->links() }}
                </div>
                @endif
            </div>
        </div>

    </div>
</x-app-layout>